<a href="http://www.cear.ufpb.br/pet">
    <img src="../images/logo_pet.png" width="150px" align="right">
</a>

<h1 align="center" style="color:blue">Biblioteca Numpy</h1>

<hr width="50%" align="center">

<h2 align="left" style="color:black">
    A biblioteca Numpy é um pacote fundamental para computação científica em Python. 
</h2>

<hr align="left" width="200px">

<h3 align="left" style="color:black">
    Com essa biblioteca é possível manipular matrizes e vetores utilizando operações matemáticas, lógicas, algebra linear e etc. 
</h3>

<hr align="left" width="200px">

> Cria arquivos do tipo __ndarray__ que são arrays n-dimensionais homogênios.

<h3 align="left" style="color:blue">
    Como importar NumPy 
</h3>

<hr align="left" width="200px">


In [2]:
import numpy as np

<h3 align="left" style="color:blue">
    Criando arrays 
</h3>

<hr align="left" width="200px">


In [4]:
a = np.array ([1, 2, 3, 4, 5, 6])


array([1, 2, 3, 4, 5, 6])

In [8]:
a = np.array([[1,2,3,4], [4,5,7,8], [9,10,11,12]])

In [9]:
print (a[0])

[1 2 3 4]


<h3 align="left" style="color:blue">
    Tipos de Array
   
</h3>

<hr align="left" width="200px">

In [10]:
#Array de Zero

np.zeros(2)

array([0., 0.])

In [12]:
#Array de ums

np.ones(2)

array([1., 1.])

In [18]:
#Array Vazio

np.empty(4)

array([9.76118064e-313, 2.56761491e-312, 2.14321575e-312, 3.95252517e-323])

In [19]:
#Array com uma faixa de elementos

np.arange(4)

array([0, 1, 2, 3])

In [20]:
#arange (primeiro numero, ultimo numero, passo)

np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [21]:
#Array de valores espaçados linearmente em um intervalo específico

np.linspace (0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

<h3 align="left" style="color:blue">
    Especificando o tipo de dado
</h3>

<hr align="left" width="200px">

In [23]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [98]:
#Copia o array, especificando o tipo

x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [99]:
x.astype(int)

array([1, 2, 2])

<h3 align="left" style="color:blue">
    Adicionando, removendo e ordenando elementos
</h3>

<hr align="left" width="200px">

In [25]:
#Criando Array

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [26]:
#Ordenando os números

np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
#Criando arrays para concatenar

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [28]:
#Concatenando

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
#Outra forma de concatenação

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [30]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

<h3 align="left" style="color:blue">
    Como saber tamanho e formato de um array
</h3>

<hr align="left" width="200px">

In [31]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [33]:
#Número de dimensões d array

array_example.ndim

3

In [34]:
#Número total de elementos

array_example.size

24

In [35]:
#Formato do array

array_example.shape

(3, 2, 4)

In [36]:
#Mudando o formato do array

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [37]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


<h3 align="left" style="color:blue">
    Como converter array 1D para 2D
</h3>

<hr align="left" width="200px">

In [39]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [40]:
#Adicionando novo eixo de linha

a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [43]:
#Adicionando novo eixo de coluna

col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

<h3 align="left" style="color:blue">
    Indexação e Slicing
</h3>

<hr align="left" width="200px">

> É possível indexar e fatiar arrays de NumPy da mesma maneira que com as listas em Python.

In [44]:
data = np.array([1, 2, 3])


In [45]:
data[1]

2

In [46]:
data[0:2]

array([1, 2])

In [47]:
data[1:]

array([2, 3])

In [48]:
data[-2:]

array([2, 3])

In [49]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [50]:
print(a[a < 5])

[1 2 3 4]


In [51]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


<h3 align="left" style="color:blue">
    Operações básicas de Array
</h3>

<hr align="left" width="200px">

In [52]:
#Soma

data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [53]:
#Subtração

data - ones

array([0, 1])

In [ ]:
#Multiplicação

data * data

In [ ]:
#Divisão

data / data

In [ ]:
#Soma dos elementos presentes em um array

a = np.array([1, 2, 3, 4])
a.sum()

In [57]:
#Se for um array 2D é necessário especificar o eixo (linha ou coluna)

b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

<h3 align="left" style="color:blue">
    Operações de array mais úteis
</h3>

<hr align="left" width="200px">

In [58]:
data = np.array([1.0, 2.0])

In [64]:
data.max()

2.0

In [65]:
data.min()

1.0

In [66]:
data.sum()

3.0

In [59]:
data.mean()

1.5

In [96]:
#Retorna o indice dos valores máximos ao longo do eixo

a = np.arange(6).reshape(2,3) 
a
np.argmax(a)

5

In [97]:
#Retorna o indice dos valores máximos ao longo do eixo

a = np.arange(6).reshape(2,3) 
a
np.argmin(a)

0

In [61]:
data.std()

0.5

In [63]:
data.prod()

2.0

<h3 align="left" style="color:blue">
    Criando matrizes
</h3>

<hr align="left" width="200px">

In [67]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

<h4 align="left" style="color:black">
    As mesmas operações utilizadas acima podem ser usadas em matrizes. 
</h4>

<hr align="left" width="200px">


In [ ]:
data.max()

In [ ]:
data.min()

In [ ]:
data.sum()

In [ ]:
data.max(axis=0)

In [ ]:
data.max(axis=1)

In [68]:
#Matrizes de mesmo tamanho

data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

<h4 align="left" style="color:black">
    Gerando números aleatórios da forma mais simples:
    
</h4>

<hr align="left" width="200px">

In [71]:
np.random.random((3,2))

array([[0.91234758, 0.96238761],
       [0.23893852, 0.42277125],
       [0.16368785, 0.9323781 ]])

<h3 align="left" style="color:blue">
    Matriz transposta e mudança de formato
</h3>

<hr align="left" width="200px">

In [73]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [74]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

<h3 align="left" style="color:blue">
    Salvando e carregando objetos de NumPy
    
</h3>

<hr align="left" width="200px">

In [80]:
a = np.array([1, 2, 3, 4, 5, 6])

In [81]:
np.save('filename', a)

In [82]:
b = np.load('filename.npy')

In [83]:
print(b)

[1 2 3 4 5 6]


In [84]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
#Usado para salvar em .csv ou .txt

np.savetxt('new_file.csv', csv_arr)

In [86]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

<div>
    <a href="https://www.ufpb.br/">
        <img src="../images/logo_ufpb.png" align="left" height="50px" width="70px">
    </a>
    <a href="http://www.cear.ufpb.br/">
        <img src="../images/logo_cear.png" align="left" width="95px">
    </a>
</div>